server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  mvc:
    log-request-details: true
  cloud:
    gateway:
      routes:
        - id: court
          uri: ${COURT_URI}
          predicates:
            - Path=/court, /court/{segment}
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: visit
          uri: ${VISIT_URI}
          predicates:
            - Path=/visit, /visit/{segment}, /visit/{segment}/{segment}
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: review
          uri: ${REVIEW_URI}
          predicates:
            - Path=/review, /review/{segment}
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type:
              - "authorization_code"
              - "refresh_token"
            redirect-uri: "${GATEWAY_URI}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          spring:
            issuer-uri: ${ISSUER_URI}


management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true