name: Deploy by runner

on:
  push:
    branches: [ "master" ]

jobs:
  jib:
    runs-on: ubuntu-latest
    steps:
        - name: JIB container
          uses: MathieuSoysal/jib-container-publish.yml@v2.1.5
          with:
            USERNAME: ${{ secrets.DOCKER_LOGIN }}
            PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            java-version: 17
          
